tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
brew "automake"
brew "bat"
brew "dotnet@8", link: true
brew "eza"
brew "fd"
brew "fzf"
brew "git"
brew "gnupg"
brew "go"
brew "libtool"
brew "libyaml"
brew "lua-language-server"
brew "luarocks"
brew "neovim"
brew "nvm"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "tmux"
brew "xz"
brew "zlib"
brew "zoxide"
brew "jesseduffield/lazydocker/lazydocker"
brew "jesseduffield/lazygit/lazygit"
cask "alt-tab"
cask "docker"
cask "hiddenbar"
cask "rectangle"
cask "stats"
cask "zoom"

# --- Added by install.sh refresh ---

# Taps for third-party CLIs
tap "oven-sh/bun"
tap "sst/tap"

# CLIs
brew "gh"
brew "mas"
brew "node"
brew "oven-sh/bun/bun"
brew "sst/tap/opencode"

# Desktop apps
cask "1password"
cask "1password-cli"
cask "notion"
cask "obsidian"
cask "raycast"
cask "slack"
cask "spotify"
cask "tailscale"
